# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('class_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('blurb', models.TextField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('live', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(max_length=40, unique=True)),
                ('commit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('path', models.CharField(max_length=128, null=True)),
                ('remote_server', models.CharField(max_length=256, null=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('branch', models.CharField(default=b'master', max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentVersion',
            fields=[
                ('label', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('release_note', models.TextField()),
                ('playlist_uid', models.CharField(max_length=40, null=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.ExperimentArchive')),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to='archives.Experiment')),
                ('playlist_ct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archives_experimentversion_as_playlist', to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='experimentarchive',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.ExperimentRepository'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='current_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentversion', to='archives.ExperimentVersion'),
        ),
    ]
