# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lexicon',
            fields=[
                ('word', models.CharField(default=b'word', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('title', models.TextField(default=b'A Text', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordlistItems',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(null=True)),
                ('lexicon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='textual.Lexicon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordlistStimulus',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordlistTestItems',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(null=True)),
                ('expected_response', models.NullBooleanField()),
                ('lexicon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='textual.Lexicon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordlistTestStimulus',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wordlisttestitems',
            name='wordlist_stimulus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='textual.WordlistTestStimulus'),
        ),
        migrations.AddField(
            model_name='wordlistitems',
            name='wordlist_stimulus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='textual.WordlistStimulus'),
        ),
    ]
