# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:52
from __future__ import unicode_literals

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CssFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', apps.core.fields.nameField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JsFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', apps.core.fields.nameField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SessionSlideAndPlaylistJoinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_uid', models.CharField(blank=True, max_length=40, null=True)),
                ('element_uid', models.CharField(blank=True, max_length=40, null=True)),
                ('rank', models.PositiveSmallIntegerField(null=True)),
                ('started', models.BooleanField(default=False)),
                ('datetime_started', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('datetime_completed', models.DateTimeField(blank=True, null=True)),
                ('container_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_sessionslideandplaylistjoinmodel_as_container', to='contenttypes.ContentType')),
                ('element_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_sessionslideandplaylistjoinmodel_as_element', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionWidgetAndSlideJoinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_uid', models.CharField(blank=True, max_length=40, null=True)),
                ('element_uid', models.CharField(blank=True, max_length=40, null=True)),
                ('rank', models.PositiveSmallIntegerField(null=True)),
                ('started', models.BooleanField(default=False)),
                ('datetime_started', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('datetime_completed', models.DateTimeField(blank=True, null=True)),
                ('widget_name', models.CharField(max_length=50, null=True)),
                ('container_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_sessionwidgetandslidejoinmodel_as_container', to='contenttypes.ContentType')),
                ('element_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_sessionwidgetandslidejoinmodel_as_element', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlideAndPlaylistJoinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_uid', models.CharField(blank=True, max_length=40, null=True)),
                ('element_uid', models.CharField(blank=True, max_length=40, null=True)),
                ('container_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_slideandplaylistjoinmodel_as_container', to='contenttypes.ContentType')),
                ('element_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_slideandplaylistjoinmodel_as_element', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlideTypes',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('app_label', apps.core.fields.nameField(blank=True, max_length=255, null=True)),
                ('name', apps.core.fields.nameField(blank=True, max_length=255, null=True)),
                ('date_initiated', apps.core.fields.DateTimeField(blank=True, null=True)),
                ('htmltemplate', apps.core.fields.nameField(blank=True, max_length=255, null=True)),
                ('cssfiles', apps.core.fields.ManyToManyField(to='base.CssFiles')),
                ('jsfiles', apps.core.fields.ManyToManyField(to='base.JsFiles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WidgetTypes',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('app_label', apps.core.fields.nameField(blank=True, max_length=255, null=True)),
                ('name', apps.core.fields.nameField(blank=True, max_length=255, null=True)),
                ('date_initiated', apps.core.fields.DateTimeField(blank=True, null=True)),
                ('htmltemplate', apps.core.fields.nameField(blank=True, max_length=255, null=True)),
                ('jstemplate', apps.core.fields.nameField(blank=True, max_length=255, null=True)),
                ('gateway', apps.core.fields.nameField(blank=True, max_length=255, null=True)),
                ('cssfiles', apps.core.fields.ManyToManyField(to='base.CssFiles')),
                ('jsfiles', apps.core.fields.ManyToManyField(to='base.JsFiles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
