# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('temp_subject', models.BooleanField(default=False)),
                ('created', models.DateTimeField(null=True)),
                ('login_method', models.CharField(blank=True, default=b'wilhelm', max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('right_handed', models.NullBooleanField()),
                ('male', models.NullBooleanField()),
                ('is_english_speaker', models.NullBooleanField()),
                ('native_language', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
