# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='fake_subject',
            field=models.BooleanField(default=False),
        ),
    ]
