# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_fake_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='fake_subject',
            new_name='test_subject',
        ),
    ]
