# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20160604_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='notify_me',
            field=models.BooleanField(default=False),
        ),
    ]
