# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_notify_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='notify_me',
            field=models.NullBooleanField(),
        ),
    ]
