# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-15 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20160614_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='notify_me',
            new_name='receive_notifications',
        ),
    ]
