# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentSession',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('playlist_session_uid', models.CharField(max_length=40, null=True)),
                ('attempt', models.IntegerField(default=0)),
                ('parts_completed', models.IntegerField(default=0)),
                ('date_started', models.DateTimeField(null=True)),
                ('last_activity', models.DateTimeField(null=True)),
                ('date_completed', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[(b'status_completed', b'Completed'), (b'status_part_completed', b'Part completed'), (b'status_initialized', b'Initiated'), (b'status_paused', b'Paused'), (b'status_live', b'Live')], max_length=255)),
                ('experiment_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.ExperimentVersion')),
                ('playlist_session_ct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mysessions_experimentsession_as_playlist_session', to='contenttypes.ContentType')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='experimentsession',
            unique_together=set([('subject', 'experiment_version', 'attempt')]),
        ),
    ]
