# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:52
from __future__ import unicode_literals

import apps.core.fields
import contrib.bartlett.widgets.widgets
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryChoiceModel',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('sessionwidget_uid', models.CharField(max_length=40, null=True)),
                ('stimulus_uid', models.CharField(max_length=40, null=True)),
                ('order', models.PositiveSmallIntegerField(null=True)),
                ('stimulus_onset_datetime', models.DateTimeField(null=True)),
                ('response_datetime', models.DateTimeField(null=True)),
                ('response', models.NullBooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('instructions', jsonfield.fields.JSONField(null=True)),
                ('max_slides', models.IntegerField(blank=True, default=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionPlaylist',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('initialized', models.BooleanField(default=False)),
                ('datetime_initialized', models.DateTimeField(null=True)),
                ('started', models.BooleanField(default=False)),
                ('datetime_started', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('datetime_completed', models.DateTimeField(null=True)),
                ('current_slide_rank', models.PositiveIntegerField(null=True)),
                ('playlist_uid', models.CharField(max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionTetris',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('initialized', models.BooleanField(default=False)),
                ('datetime_initialized', models.DateTimeField(null=True)),
                ('started', models.BooleanField(default=False)),
                ('datetime_started', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('datetime_completed', models.DateTimeField(null=True)),
                ('widget_uid', models.CharField(max_length=40, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionTextDisplay',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('initialized', models.BooleanField(default=False)),
                ('datetime_initialized', models.DateTimeField(null=True)),
                ('started', models.BooleanField(default=False)),
                ('datetime_started', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('datetime_completed', models.DateTimeField(null=True)),
                ('widget_uid', models.CharField(max_length=40, null=True)),
                ('text_display_start', apps.core.fields.DateTimeField(blank=True, null=True)),
                ('text_display_stop', apps.core.fields.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionTextRecallMemoryTest',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('initialized', models.BooleanField(default=False)),
                ('datetime_initialized', models.DateTimeField(null=True)),
                ('started', models.BooleanField(default=False)),
                ('datetime_started', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('datetime_completed', models.DateTimeField(null=True)),
                ('slide_uid', models.CharField(max_length=40, null=True)),
                ('ping_uid', models.CharField(max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionTextRecognitionMemoryTest',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('initialized', models.BooleanField(default=False)),
                ('datetime_initialized', models.DateTimeField(null=True)),
                ('started', models.BooleanField(default=False)),
                ('datetime_started', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('datetime_completed', models.DateTimeField(null=True)),
                ('slide_uid', models.CharField(max_length=40, null=True)),
                ('ping_uid', models.CharField(max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionWordlistDisplay',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('initialized', models.BooleanField(default=False)),
                ('datetime_initialized', models.DateTimeField(null=True)),
                ('started', models.BooleanField(default=False)),
                ('datetime_started', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('datetime_completed', models.DateTimeField(null=True)),
                ('widget_uid', models.CharField(max_length=40, null=True)),
                ('wordlist_permutation', apps.core.fields.jsonField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionWordlistRecallMemoryTest',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('initialized', models.BooleanField(default=False)),
                ('datetime_initialized', models.DateTimeField(null=True)),
                ('started', models.BooleanField(default=False)),
                ('datetime_started', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('datetime_completed', models.DateTimeField(null=True)),
                ('slide_uid', models.CharField(max_length=40, null=True)),
                ('ping_uid', models.CharField(max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionWordlistRecognitionMemoryTest',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('initialized', models.BooleanField(default=False)),
                ('datetime_initialized', models.DateTimeField(null=True)),
                ('started', models.BooleanField(default=False)),
                ('datetime_started', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('datetime_completed', models.DateTimeField(null=True)),
                ('slide_uid', models.CharField(max_length=40, null=True)),
                ('ping_uid', models.CharField(max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'SessWrdLstRecogMemTest',
            },
        ),
        migrations.CreateModel(
            name='SessionWordRecallTest',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('initialized', models.BooleanField(default=False)),
                ('datetime_initialized', models.DateTimeField(null=True)),
                ('started', models.BooleanField(default=False)),
                ('datetime_started', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('datetime_completed', models.DateTimeField(null=True)),
                ('widget_uid', models.CharField(max_length=40, null=True)),
                ('recalledwords_json', jsonfield.fields.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionWordRecognitionTest',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('initialized', models.BooleanField(default=False)),
                ('datetime_initialized', models.DateTimeField(null=True)),
                ('started', models.BooleanField(default=False)),
                ('datetime_started', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('datetime_completed', models.DateTimeField(null=True)),
                ('widget_uid', models.CharField(max_length=40, null=True)),
                ('wordlist_permutation', apps.core.fields.jsonField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tetris',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('start_msg', apps.core.fields.TextField(blank=True, null=True)),
                ('duration', models.FloatField(default=120, null=True)),
                ('speed', models.FloatField(default=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextDisplay',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('start_msg', apps.core.fields.TextField(blank=True, null=True)),
                ('minimum_reading_time', models.FloatField(default=60, null=True)),
                ('maximum_reading_time', models.FloatField(default=180, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextRecallMemoryTest',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', apps.core.fields.nameField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextRecognitionMemoryTest',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', apps.core.fields.nameField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordlistDisplay',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('start_msg', apps.core.fields.TextField(blank=True, null=True)),
                ('isi', models.FloatField(default=0.2, null=True)),
                ('fadeInDuration', models.FloatField(default=0.2, null=True)),
                ('fadeOutDuration', models.FloatField(default=0.2, null=True)),
                ('stimulusDuration', models.FloatField(default=3, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, contrib.bartlett.widgets.widgets.WordlistMixin),
        ),
        migrations.CreateModel(
            name='WordlistRecallMemoryTest',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', apps.core.fields.nameField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordlistRecognitionMemoryTest',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', apps.core.fields.nameField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordRecallTest',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('start_msg', apps.core.fields.TextField(blank=True, null=True)),
                ('option_length', apps.core.fields.PositiveSmallIntegerField(blank=True, default=5, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordRecognitionTest',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('start_msg', apps.core.fields.TextField(blank=True, null=True)),
                ('isi', models.FloatField(default=0.2)),
                ('fadeInDuration', models.FloatField(default=0.2)),
                ('fadeOutDuration', models.FloatField(default=0.2)),
                ('timeOutDuration', models.FloatField(default=3)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, contrib.bartlett.widgets.widgets.WordlistMixin),
        ),
    ]
