# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:52
from __future__ import unicode_literals

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('textual', '0001_initial'),
        ('bartlett', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordrecognitiontest',
            name='widgettype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_wordrecognitiontest_as_element', to='base.WidgetTypes'),
        ),
        migrations.AddField(
            model_name='wordrecognitiontest',
            name='wordliststimulus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='textual.WordlistTestStimulus'),
        ),
        migrations.AddField(
            model_name='wordrecalltest',
            name='widgettype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_wordrecalltest_as_element', to='base.WidgetTypes'),
        ),
        migrations.AddField(
            model_name='wordlistrecognitionmemorytest',
            name='slide_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_wordlistrecognitionmemorytest_as_element', to='base.SlideTypes'),
        ),
        migrations.AddField(
            model_name='wordlistrecognitionmemorytest',
            name='tetris',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bartlett.Tetris'),
        ),
        migrations.AddField(
            model_name='wordlistrecognitionmemorytest',
            name='word_recognition_test',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bartlett.WordRecognitionTest'),
        ),
        migrations.AddField(
            model_name='wordlistrecognitionmemorytest',
            name='wordlist_display',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bartlett.WordlistDisplay'),
        ),
        migrations.AddField(
            model_name='wordlistrecallmemorytest',
            name='slide_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_wordlistrecallmemorytest_as_element', to='base.SlideTypes'),
        ),
        migrations.AddField(
            model_name='wordlistrecallmemorytest',
            name='tetris',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bartlett.Tetris'),
        ),
        migrations.AddField(
            model_name='wordlistrecallmemorytest',
            name='word_recall',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bartlett.WordRecallTest'),
        ),
        migrations.AddField(
            model_name='wordlistrecallmemorytest',
            name='wordlist_display',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bartlett.WordlistDisplay'),
        ),
        migrations.AddField(
            model_name='wordlistdisplay',
            name='widgettype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_wordlistdisplay_as_element', to='base.WidgetTypes'),
        ),
        migrations.AddField(
            model_name='wordlistdisplay',
            name='wordliststimulus',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textual.WordlistStimulus'),
        ),
        migrations.AddField(
            model_name='textrecognitionmemorytest',
            name='slide_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_textrecognitionmemorytest_as_element', to='base.SlideTypes'),
        ),
        migrations.AddField(
            model_name='textrecognitionmemorytest',
            name='tetris',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bartlett.Tetris'),
        ),
        migrations.AddField(
            model_name='textrecognitionmemorytest',
            name='text_display',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bartlett.TextDisplay'),
        ),
        migrations.AddField(
            model_name='textrecognitionmemorytest',
            name='word_recognition_test',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bartlett.WordRecognitionTest'),
        ),
        migrations.AddField(
            model_name='textrecallmemorytest',
            name='slide_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_textrecallmemorytest_as_element', to='base.SlideTypes'),
        ),
        migrations.AddField(
            model_name='textrecallmemorytest',
            name='tetris',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bartlett.Tetris'),
        ),
        migrations.AddField(
            model_name='textrecallmemorytest',
            name='text_display',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bartlett.TextDisplay'),
        ),
        migrations.AddField(
            model_name='textrecallmemorytest',
            name='word_recall',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bartlett.WordRecallTest'),
        ),
        migrations.AddField(
            model_name='textdisplay',
            name='textstimulus',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textual.TextStimulus'),
        ),
        migrations.AddField(
            model_name='textdisplay',
            name='widgettype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_textdisplay_as_element', to='base.WidgetTypes'),
        ),
        migrations.AddField(
            model_name='tetris',
            name='widgettype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_tetris_as_element', to='base.WidgetTypes'),
        ),
        migrations.AddField(
            model_name='sessionwordrecognitiontest',
            name='widget_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_sessionwordrecognitiontest_as_widget', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sessionwordrecalltest',
            name='widget_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_sessionwordrecalltest_as_widget', to='contenttypes.ContentType'),
        ),
    ]
