# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:52
from __future__ import unicode_literals

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bartlett', '0002_auto_20160216_2052'),
        ('textual', '0001_initial'),
        ('presenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionwordlistrecognitionmemorytest',
            name='live_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presenter.LiveExperimentSession'),
        ),
        migrations.AddField(
            model_name='sessionwordlistrecognitionmemorytest',
            name='slide_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_sessionwordlistrecognitionmemorytest_as_slide', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sessionwordlistrecallmemorytest',
            name='live_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presenter.LiveExperimentSession'),
        ),
        migrations.AddField(
            model_name='sessionwordlistrecallmemorytest',
            name='slide_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_sessionwordlistrecallmemorytest_as_slide', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sessionwordlistdisplay',
            name='widget_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_sessionwordlistdisplay_as_widget', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sessionwordlistdisplay',
            name='wordliststimulus',
            field=apps.core.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textual.WordlistStimulus'),
        ),
        migrations.AddField(
            model_name='sessiontextrecognitionmemorytest',
            name='live_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presenter.LiveExperimentSession'),
        ),
        migrations.AddField(
            model_name='sessiontextrecognitionmemorytest',
            name='slide_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_sessiontextrecognitionmemorytest_as_slide', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sessiontextrecallmemorytest',
            name='live_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presenter.LiveExperimentSession'),
        ),
        migrations.AddField(
            model_name='sessiontextrecallmemorytest',
            name='slide_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_sessiontextrecallmemorytest_as_slide', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sessiontextdisplay',
            name='widget_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_sessiontextdisplay_as_widget', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sessiontetris',
            name='widget_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_sessiontetris_as_widget', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sessionplaylist',
            name='playlist_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_sessionplaylist_as_playlist', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='binarychoicemodel',
            name='sessionwidget_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_binarychoicemodel_as_sessionwidget', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='binarychoicemodel',
            name='stimulus_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bartlett_binarychoicemodel_as_stimulus', to='contenttypes.ContentType'),
        ),
    ]
