# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 16:19
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bartlett', '0003_auto_20160216_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='misc',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
