# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 15:01
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bartlett', '0005_playlistv2_sessionplaylistv2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionwordlistdisplay',
            name='_wordlist',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
