# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentDataExport',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('short_uid', models.CharField(max_length=7, null=True, unique=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('filename', models.CharField(max_length=100, null=True)),
                ('attachment_filename', models.CharField(max_length=100, null=True)),
                ('checksums', jsonfield.fields.JSONField(null=True)),
                ('filesize', models.CharField(max_length=100, null=True)),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.Experiment')),
            ],
        ),
    ]
